"""Golden wire fixtures for the mojosearch entities selftest.

Generated by tools/gen_fixture_literals.py from the application's
captured nearby payload; do not hand-edit the bytes.

origin: alugue-mojo-api payloads/nearby_300.json
"""

from mojoflask import BytePtr

from mojosearch.entities import (
    ListingJson,
    NearbyListingRow,
    Price,
    photo_entries_from_list,
)
from mojoserde import AlwaysNull, Arr, TimestampMicros

from mojosearch.web.numeric_core import (
    parse_postgres_timestamp_nearby_bytes,
)


def microseconds_of_row_timestamp_text(text: String) -> Int64:
    var text_bytes = text.as_bytes()
    var text_pointer = BytePtr(unsafe_from_address=Int(text_bytes.unsafe_ptr()))
    return parse_postgres_timestamp_nearby_bytes(text_pointer, len(text_bytes))


alias GOLDEN_NEARBY_ITEM_0_TEXT = "{\"id\":11686911,\"advertiser_id\":637,\"latitude\":-23.5505,\"longitude\":-46.6333,\"title\":\"Espaço Bem-Estar Centro\",\"description\":\"\",\"street\":\"Rua das Acácias\",\"house_number\":150,\"complement\":\"\",\"contact_phone\":\"\",\"period\":\"H\",\"daily_price\":0.0,\"weekly_price\":0.0,\"monthly_price\":0.0,\"yearly_price\":0.0,\"hourly_price\":55.0,\"period_price\":0.0,\"created_at\":\"2026-08-14T17:51:07.875448\",\"miles\":0.0,\"filters\":[7502,25,60,7349,7412,7418,6060,5993,6069,7324,6065,6059],\"photos\":[\"fotos/extractor/sublocando/4a8b78e6-772a-4fb4-a771-b19643dc7d5c/005.png\",\"fotos/extractor/sublocando/4a8b78e6-772a-4fb4-a771-b19643dc7d5c/002.png\",\"fotos/extractor/sublocando/4a8b78e6-772a-4fb4-a771-b19643dc7d5c/004.png\",\"fotos/extractor/sublocando/4a8b78e6-772a-4fb4-a771-b19643dc7d5c/003.png\"],\"review_rate\":0,\"quality_score\":57,\"median_rating\":null,\"is_favorite\":0,\"count_total\":0}"


def build_golden_nearby_item_0() -> ListingJson:
    return ListingJson(
        id=11686911,
        advertiser_id=637,
        latitude=-23.5505,
        longitude=-46.6333,
        title=String("Espaço Bem-Estar Centro"),
        description=String(""),
        street=String("Rua das Acácias"),
        house_number=Optional[Int32](150),
        complement=String(""),
        contact_phone=String(""),
        neighborhood=String(""),
        city=String(""),
        state=String(""),
        zip_code=String(""),
        period=String("H"),
        daily_price=Price(0.0),
        weekly_price=Price(0.0),
        monthly_price=Price(0.0),
        yearly_price=Price(0.0),
        hourly_price=Price(55.0),
        period_price=Price(0.0),
        created_at=TimestampMicros(microseconds_of_row_timestamp_text("2026-08-14T17:51:07.875448")),
        miles=Price(0.0),
        filters=Arr[Int32](items=[7502, 25, 60, 7349, 7412, 7418, 6060, 5993, 6069, 7324, 6065, 6059]),
        photos=photo_entries_from_list(["fotos/extractor/sublocando/4a8b78e6-772a-4fb4-a771-b19643dc7d5c/005.png", "fotos/extractor/sublocando/4a8b78e6-772a-4fb4-a771-b19643dc7d5c/002.png", "fotos/extractor/sublocando/4a8b78e6-772a-4fb4-a771-b19643dc7d5c/004.png", "fotos/extractor/sublocando/4a8b78e6-772a-4fb4-a771-b19643dc7d5c/003.png"]),
        review_rate=0,
        quality_score=Optional[Int32](57),
        median_rating=AlwaysNull(),
        is_favorite=0,
        count_total=0,
    )


alias GOLDEN_NEARBY_ITEM_3_TEXT = "{\"id\":780,\"advertiser_id\":168,\"latitude\":-23.5505199,\"longitude\":-46.63330940000003,\"title\":\"Andrea\",\"description\":\"\",\"street\":\"\",\"house_number\":null,\"complement\":\"\",\"contact_phone\":\"\",\"period\":\"H\",\"daily_price\":0.0,\"weekly_price\":0.0,\"monthly_price\":0.0,\"yearly_price\":0.0,\"hourly_price\":0.0,\"period_price\":0.0,\"created_at\":\"2026-07-31T20:03:15.336282\",\"miles\":0.001493694039310427,\"filters\":[60,7103,5985,6074,6060,7441,7391,7328,7348,7321,7502,7349],\"photos\":[\"fotos/extractor/salaja/andrea-2/001.jpg\",\"fotos/extractor/salaja/andrea-2/002.jpg\"],\"review_rate\":0,\"quality_score\":34,\"median_rating\":null,\"is_favorite\":0,\"count_total\":0}"


def build_golden_nearby_item_3() -> ListingJson:
    return ListingJson(
        id=780,
        advertiser_id=168,
        latitude=-23.5505199,
        longitude=-46.63330940000003,
        title=String("Andrea"),
        description=String(""),
        street=String(""),
        house_number=Optional[Int32](),
        complement=String(""),
        contact_phone=String(""),
        neighborhood=String(""),
        city=String(""),
        state=String(""),
        zip_code=String(""),
        period=String("H"),
        daily_price=Price(0.0),
        weekly_price=Price(0.0),
        monthly_price=Price(0.0),
        yearly_price=Price(0.0),
        hourly_price=Price(0.0),
        period_price=Price(0.0),
        created_at=TimestampMicros(microseconds_of_row_timestamp_text("2026-07-31T20:03:15.336282")),
        miles=Price(0.001493694039310427),
        filters=Arr[Int32](items=[60, 7103, 5985, 6074, 6060, 7441, 7391, 7328, 7348, 7321, 7502, 7349]),
        photos=photo_entries_from_list(["fotos/extractor/salaja/andrea-2/001.jpg", "fotos/extractor/salaja/andrea-2/002.jpg"]),
        review_rate=0,
        quality_score=Optional[Int32](34),
        median_rating=AlwaysNull(),
        is_favorite=0,
        count_total=0,
    )


alias GOLDEN_NEARBY_ITEM_10_TEXT = "{\"id\":11692979,\"advertiser_id\":999000101,\"latitude\":-23.5543,\"longitude\":-46.6351,\"title\":\"Spaces Sao Paulo, Spaces Liberdade\",\"description\":\"\",\"street\":\"Av. da Liberdade, 151 - 2, 3 e 4 andares, Liberdade\",\"house_number\":null,\"complement\":\"\",\"contact_phone\":\"\",\"period\":\"M\",\"daily_price\":0.0,\"weekly_price\":0.0,\"monthly_price\":0.0,\"yearly_price\":0.0,\"hourly_price\":0.0,\"period_price\":0.0,\"created_at\":\"2026-08-20T19:12:30.085191\",\"miles\":0.285354848969518,\"filters\":[6060,7017,7300,7301,7326],\"photos\":[],\"review_rate\":0,\"median_rating\":null,\"is_favorite\":0,\"count_total\":0}"


def build_golden_nearby_item_10() -> ListingJson:
    return ListingJson(
        id=11692979,
        advertiser_id=999000101,
        latitude=-23.5543,
        longitude=-46.6351,
        title=String("Spaces Sao Paulo, Spaces Liberdade"),
        description=String(""),
        street=String("Av. da Liberdade, 151 - 2, 3 e 4 andares, Liberdade"),
        house_number=Optional[Int32](),
        complement=String(""),
        contact_phone=String(""),
        neighborhood=String(""),
        city=String(""),
        state=String(""),
        zip_code=String(""),
        period=String("M"),
        daily_price=Price(0.0),
        weekly_price=Price(0.0),
        monthly_price=Price(0.0),
        yearly_price=Price(0.0),
        hourly_price=Price(0.0),
        period_price=Price(0.0),
        created_at=TimestampMicros(microseconds_of_row_timestamp_text("2026-08-20T19:12:30.085191")),
        miles=Price(0.285354848969518),
        filters=Arr[Int32](items=[6060, 7017, 7300, 7301, 7326]),
        photos=photo_entries_from_list([]),
        review_rate=0,
        quality_score=Optional[Int32](),
        median_rating=AlwaysNull(),
        is_favorite=0,
        count_total=0,
    )


def build_golden_nearby_row_item_0() -> NearbyListingRow:
    var nearby_row = NearbyListingRow()
    nearby_row.id = 11686911
    nearby_row.advertiser_id = 637
    nearby_row.latitude = -23.5505
    nearby_row.longitude = -46.6333
    nearby_row.title = String("Espaço Bem-Estar Centro")
    nearby_row.street = String("Rua das Acácias")
    nearby_row.house_number = Optional[Int32](150)
    nearby_row.complement = String("")
    nearby_row.period = String("H")
    nearby_row.daily_price = 0.0
    nearby_row.weekly_price = 0.0
    nearby_row.monthly_price = 0.0
    nearby_row.yearly_price = 0.0
    nearby_row.hourly_price = 55.0
    nearby_row.period_price = 0.0
    nearby_row.data_anuncio = String("2026-08-14 17:51:07.875448+00")
    nearby_row.filters = [7502, 25, 60, 7349, 7412, 7418, 6060, 5993, 6069, 7324, 6065, 6059]
    nearby_row.photos = ["fotos/extractor/sublocando/4a8b78e6-772a-4fb4-a771-b19643dc7d5c/005.png", "fotos/extractor/sublocando/4a8b78e6-772a-4fb4-a771-b19643dc7d5c/002.png", "fotos/extractor/sublocando/4a8b78e6-772a-4fb4-a771-b19643dc7d5c/004.png", "fotos/extractor/sublocando/4a8b78e6-772a-4fb4-a771-b19643dc7d5c/003.png"]
    nearby_row.review_rate = 0
    nearby_row.quality_score = Optional[Int32](57)
    nearby_row.distance = 0.0
    return nearby_row^

